name    'bascht-yakshed'
version '0.1.0'
source 'UNKNOWN'
author 'bascht'
license 'GNU LGPL v3.0'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'

## Add dependencies, if any:
dependency 'puppetlabs/apt', '>= 1.7.0'
dependency 'puppetlabs/stdlib', '>= 4.4.0'
dependency 'puppetlabs/ntp', '>= '3.0.2'
dependency 'attachmentgenie/ufw', '>=1.4.7'
dependency 'saz/locales', '>= 2.0.1'